image: golang:1.25-alpine

stages:
  - lint
  - test
  - build

before_script:
  - apk add --no-cache npm make
  - npm install

lint:
  stage: lint
  script:
    - go vet ./...
    - go fmt ./...
  allow_failure: false

test:
  stage: test
  script:
    - go test -v -count=1 ./...
  coverage: '/\d+\.\d+% of statements/'

build:
  stage: build
  script:
    - go build -o /dev/null ./cmd/server
  artifacts:
    paths:
      - durpdeploy
    expire_in: 1 week
  needs: ["lint", "test"]
