image: golang:1.25-alpine

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - go vet ./...
    - test -z "$(gofmt -l .)"
  allow_failure: false

test:
  stage: test
  script:
    - go test -v -count=1 ./...
  coverage: '/\d+\.\d+% of statements/'

build:
  stage: build
  script:
    - go build -o durpdeploy ./cmd/server
  artifacts:
    paths:
      - durpdeploy
    expire_in: 1 week
  needs: ["lint", "test"]
