// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (release_id, environment_id, status, started_at, finished_at) VALUES (?, ?, ?, ?, ?) RETURNING id, release_id, environment_id, status, started_at, finished_at, created_at
`

type CreateDeploymentParams struct {
	ReleaseID     int64         `json:"release_id"`
	EnvironmentID int64         `json:"environment_id"`
	Status        string        `json:"status"`
	StartedAt     sql.NullInt64 `json:"started_at"`
	FinishedAt    sql.NullInt64 `json:"finished_at"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ReleaseID,
		arg.EnvironmentID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments WHERE id = ?
`

func (q *Queries) DeleteDeployment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, id)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at FROM deployments WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at FROM deployments ORDER BY created_at DESC
`

func (q *Queries) ListDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByRelease = `-- name: ListDeploymentsByRelease :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at FROM deployments WHERE release_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByRelease(ctx context.Context, releaseID int64) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeployments = `-- name: ListRecentDeployments :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at FROM deployments ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRecentDeployments(ctx context.Context, limit int64) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeployments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE deployments SET release_id = ?, environment_id = ?, status = ?, started_at = ?, finished_at = ? WHERE id = ? RETURNING id, release_id, environment_id, status, started_at, finished_at, created_at
`

type UpdateDeploymentParams struct {
	ReleaseID     int64         `json:"release_id"`
	EnvironmentID int64         `json:"environment_id"`
	Status        string        `json:"status"`
	StartedAt     sql.NullInt64 `json:"started_at"`
	FinishedAt    sql.NullInt64 `json:"finished_at"`
	ID            int64         `json:"id"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeployment,
		arg.ReleaseID,
		arg.EnvironmentID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments SET status = ?, started_at = ?, finished_at = ? WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status     string        `json:"status"`
	StartedAt  sql.NullInt64 `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
