// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createDeploymentLog = `-- name: CreateDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, step_name, line) VALUES (?, ?, ?) RETURNING id, deployment_id, step_name, line, created_at
`

type CreateDeploymentLogParams struct {
	DeploymentID int64          `json:"deployment_id"`
	StepName     sql.NullString `json:"step_name"`
	Line         string         `json:"line"`
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentLog, arg.DeploymentID, arg.StepName, arg.Line)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeploymentLog = `-- name: DeleteDeploymentLog :exec
DELETE FROM deployment_logs WHERE id = ?
`

func (q *Queries) DeleteDeploymentLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentLog, id)
	return err
}

const getDeploymentLog = `-- name: GetDeploymentLog :one
SELECT id, deployment_id, step_name, line, created_at FROM deployment_logs WHERE id = ?
`

func (q *Queries) GetDeploymentLog(ctx context.Context, id int64) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentLog, id)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentLogsByDeployment = `-- name: ListDeploymentLogsByDeployment :many
SELECT id, deployment_id, step_name, line, created_at FROM deployment_logs WHERE deployment_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentLogsByDeployment(ctx context.Context, deploymentID int64) ([]DeploymentLog, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentLogsByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.StepName,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentLog = `-- name: UpdateDeploymentLog :one
UPDATE deployment_logs SET deployment_id = ?, step_name = ?, line = ? WHERE id = ? RETURNING id, deployment_id, step_name, line, created_at
`

type UpdateDeploymentLogParams struct {
	DeploymentID int64          `json:"deployment_id"`
	StepName     sql.NullString `json:"step_name"`
	Line         string         `json:"line"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateDeploymentLog(ctx context.Context, arg UpdateDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, updateDeploymentLog,
		arg.DeploymentID,
		arg.StepName,
		arg.Line,
		arg.ID,
	)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}
