// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lifecycles.sql

package db

import (
	"context"
	"database/sql"
)

const createLifecycle = `-- name: CreateLifecycle :one
INSERT INTO lifecycles (name, description) VALUES (?, ?) RETURNING id, name, description, created_at
`

type CreateLifecycleParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateLifecycle(ctx context.Context, arg CreateLifecycleParams) (Lifecycle, error) {
	row := q.db.QueryRowContext(ctx, createLifecycle, arg.Name, arg.Description)
	var i Lifecycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createLifecycleStage = `-- name: CreateLifecycleStage :one
INSERT INTO lifecycle_stages (lifecycle_id, environment_id, sort_order) VALUES (?, ?, ?) RETURNING id, lifecycle_id, environment_id, sort_order
`

type CreateLifecycleStageParams struct {
	LifecycleID   int64 `json:"lifecycle_id"`
	EnvironmentID int64 `json:"environment_id"`
	SortOrder     int64 `json:"sort_order"`
}

func (q *Queries) CreateLifecycleStage(ctx context.Context, arg CreateLifecycleStageParams) (LifecycleStage, error) {
	row := q.db.QueryRowContext(ctx, createLifecycleStage, arg.LifecycleID, arg.EnvironmentID, arg.SortOrder)
	var i LifecycleStage
	err := row.Scan(
		&i.ID,
		&i.LifecycleID,
		&i.EnvironmentID,
		&i.SortOrder,
	)
	return i, err
}

const deleteLifecycle = `-- name: DeleteLifecycle :exec
DELETE FROM lifecycles WHERE id = ?
`

func (q *Queries) DeleteLifecycle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLifecycle, id)
	return err
}

const deleteLifecycleStage = `-- name: DeleteLifecycleStage :exec
DELETE FROM lifecycle_stages WHERE id = ?
`

func (q *Queries) DeleteLifecycleStage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLifecycleStage, id)
	return err
}

const deleteLifecycleStagesByLifecycle = `-- name: DeleteLifecycleStagesByLifecycle :exec
DELETE FROM lifecycle_stages WHERE lifecycle_id = ?
`

func (q *Queries) DeleteLifecycleStagesByLifecycle(ctx context.Context, lifecycleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLifecycleStagesByLifecycle, lifecycleID)
	return err
}

const getLifecycle = `-- name: GetLifecycle :one
SELECT id, name, description, created_at FROM lifecycles WHERE id = ?
`

func (q *Queries) GetLifecycle(ctx context.Context, id int64) (Lifecycle, error) {
	row := q.db.QueryRowContext(ctx, getLifecycle, id)
	var i Lifecycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getLifecycleStage = `-- name: GetLifecycleStage :one
SELECT id, lifecycle_id, environment_id, sort_order FROM lifecycle_stages WHERE id = ?
`

func (q *Queries) GetLifecycleStage(ctx context.Context, id int64) (LifecycleStage, error) {
	row := q.db.QueryRowContext(ctx, getLifecycleStage, id)
	var i LifecycleStage
	err := row.Scan(
		&i.ID,
		&i.LifecycleID,
		&i.EnvironmentID,
		&i.SortOrder,
	)
	return i, err
}

const listLifecycleStageEnvironmentIDs = `-- name: ListLifecycleStageEnvironmentIDs :many
SELECT environment_id FROM lifecycle_stages WHERE lifecycle_id = ?
`

func (q *Queries) ListLifecycleStageEnvironmentIDs(ctx context.Context, lifecycleID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycleStageEnvironmentIDs, lifecycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var environment_id int64
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleStages = `-- name: ListLifecycleStages :many
SELECT id, lifecycle_id, environment_id, sort_order FROM lifecycle_stages WHERE lifecycle_id = ? ORDER BY sort_order
`

func (q *Queries) ListLifecycleStages(ctx context.Context, lifecycleID int64) ([]LifecycleStage, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycleStages, lifecycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LifecycleStage
	for rows.Next() {
		var i LifecycleStage
		if err := rows.Scan(
			&i.ID,
			&i.LifecycleID,
			&i.EnvironmentID,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycles = `-- name: ListLifecycles :many
SELECT id, name, description, created_at FROM lifecycles ORDER BY name
`

func (q *Queries) ListLifecycles(ctx context.Context) ([]Lifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lifecycle
	for rows.Next() {
		var i Lifecycle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLifecycle = `-- name: UpdateLifecycle :one
UPDATE lifecycles SET name = ?, description = ? WHERE id = ? RETURNING id, name, description, created_at
`

type UpdateLifecycleParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateLifecycle(ctx context.Context, arg UpdateLifecycleParams) (Lifecycle, error) {
	row := q.db.QueryRowContext(ctx, updateLifecycle, arg.Name, arg.Description, arg.ID)
	var i Lifecycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateLifecycleStage = `-- name: UpdateLifecycleStage :one
UPDATE lifecycle_stages SET environment_id = ?, sort_order = ? WHERE id = ? RETURNING id, lifecycle_id, environment_id, sort_order
`

type UpdateLifecycleStageParams struct {
	EnvironmentID int64 `json:"environment_id"`
	SortOrder     int64 `json:"sort_order"`
	ID            int64 `json:"id"`
}

func (q *Queries) UpdateLifecycleStage(ctx context.Context, arg UpdateLifecycleStageParams) (LifecycleStage, error) {
	row := q.db.QueryRowContext(ctx, updateLifecycleStage, arg.EnvironmentID, arg.SortOrder, arg.ID)
	var i LifecycleStage
	err := row.Scan(
		&i.ID,
		&i.LifecycleID,
		&i.EnvironmentID,
		&i.SortOrder,
	)
	return i, err
}
