// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Deployment struct {
	ID            int64         `json:"id"`
	ReleaseID     int64         `json:"release_id"`
	EnvironmentID int64         `json:"environment_id"`
	Status        string        `json:"status"`
	StartedAt     sql.NullInt64 `json:"started_at"`
	FinishedAt    sql.NullInt64 `json:"finished_at"`
	CreatedAt     int64         `json:"created_at"`
	Forced        int64         `json:"forced"`
}

type DeploymentLog struct {
	ID           int64          `json:"id"`
	DeploymentID int64          `json:"deployment_id"`
	StepName     sql.NullString `json:"step_name"`
	Line         string         `json:"line"`
	CreatedAt    int64          `json:"created_at"`
}

type Environment struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	CreatedAt   int64          `json:"created_at"`
}

type Lifecycle struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   int64          `json:"created_at"`
}

type LifecycleStage struct {
	ID            int64 `json:"id"`
	LifecycleID   int64 `json:"lifecycle_id"`
	EnvironmentID int64 `json:"environment_id"`
	SortOrder     int64 `json:"sort_order"`
}

type Project struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   int64          `json:"created_at"`
	LifecycleID sql.NullInt64  `json:"lifecycle_id"`
}

type Release struct {
	ID        int64  `json:"id"`
	ProjectID int64  `json:"project_id"`
	Version   string `json:"version"`
	StepsJson string `json:"steps_json"`
	CreatedAt int64  `json:"created_at"`
}

type ReleaseVariable struct {
	ID            int64          `json:"id"`
	ReleaseID     int64          `json:"release_id"`
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
	CreatedAt     int64          `json:"created_at"`
}

type Step struct {
	ID         int64  `json:"id"`
	ProjectID  int64  `json:"project_id"`
	Name       string `json:"name"`
	ScriptBody string `json:"script_body"`
	SortOrder  int64  `json:"sort_order"`
	CreatedAt  int64  `json:"created_at"`
}

type StepTemplate struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	ScriptBody string `json:"script_body"`
	CreatedAt  int64  `json:"created_at"`
}

type Variable struct {
	ID            int64          `json:"id"`
	ProjectID     int64          `json:"project_id"`
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
	CreatedAt     int64          `json:"created_at"`
}
