// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const clearProjectLifecycle = `-- name: ClearProjectLifecycle :exec
UPDATE projects SET lifecycle_id = NULL WHERE id = ?
`

func (q *Queries) ClearProjectLifecycle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearProjectLifecycle, id)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description) VALUES (?, ?) RETURNING id, name, description, created_at, lifecycle_id
`

type CreateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LifecycleID,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, created_at, lifecycle_id FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LifecycleID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, created_at, lifecycle_id FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LifecycleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectLifecycle = `-- name: SetProjectLifecycle :exec
UPDATE projects SET lifecycle_id = ? WHERE id = ?
`

type SetProjectLifecycleParams struct {
	LifecycleID sql.NullInt64 `json:"lifecycle_id"`
	ID          int64         `json:"id"`
}

func (q *Queries) SetProjectLifecycle(ctx context.Context, arg SetProjectLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, setProjectLifecycle, arg.LifecycleID, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = ?, description = ? WHERE id = ? RETURNING id, name, description, created_at, lifecycle_id
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LifecycleID,
	)
	return i, err
}
