// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package db

import (
	"context"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (project_id, version, steps_json) VALUES (?, ?, ?) RETURNING id, project_id, version, steps_json, created_at
`

type CreateReleaseParams struct {
	ProjectID int64  `json:"project_id"`
	Version   string `json:"version"`
	StepsJson string `json:"steps_json"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, createRelease, arg.ProjectID, arg.Version, arg.StepsJson)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.StepsJson,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases WHERE id = ?
`

func (q *Queries) DeleteRelease(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelease, id)
	return err
}

const getRelease = `-- name: GetRelease :one
SELECT id, project_id, version, steps_json, created_at FROM releases WHERE id = ?
`

func (q *Queries) GetRelease(ctx context.Context, id int64) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.StepsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listReleasesByProject = `-- name: ListReleasesByProject :many
SELECT id, project_id, version, steps_json, created_at FROM releases WHERE project_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListReleasesByProject(ctx context.Context, projectID int64) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.StepsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases SET project_id = ?, version = ?, steps_json = ? WHERE id = ? RETURNING id, project_id, version, steps_json, created_at
`

type UpdateReleaseParams struct {
	ProjectID int64  `json:"project_id"`
	Version   string `json:"version"`
	StepsJson string `json:"steps_json"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateRelease,
		arg.ProjectID,
		arg.Version,
		arg.StepsJson,
		arg.ID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.StepsJson,
		&i.CreatedAt,
	)
	return i, err
}
