// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: release_variables.sql

package db

import (
	"context"
	"database/sql"
)

const createReleaseVariable = `-- name: CreateReleaseVariable :one
INSERT INTO release_variables (release_id, name, value, environment_id) VALUES (?, ?, ?, ?) RETURNING id, release_id, name, value, environment_id, created_at
`

type CreateReleaseVariableParams struct {
	ReleaseID     int64          `json:"release_id"`
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
}

func (q *Queries) CreateReleaseVariable(ctx context.Context, arg CreateReleaseVariableParams) (ReleaseVariable, error) {
	row := q.db.QueryRowContext(ctx, createReleaseVariable,
		arg.ReleaseID,
		arg.Name,
		arg.Value,
		arg.EnvironmentID,
	)
	var i ReleaseVariable
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReleaseVariable = `-- name: DeleteReleaseVariable :exec
DELETE FROM release_variables WHERE id = ?
`

func (q *Queries) DeleteReleaseVariable(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseVariable, id)
	return err
}

const getReleaseVariable = `-- name: GetReleaseVariable :one
SELECT id, release_id, name, value, environment_id, created_at FROM release_variables WHERE id = ?
`

func (q *Queries) GetReleaseVariable(ctx context.Context, id int64) (ReleaseVariable, error) {
	row := q.db.QueryRowContext(ctx, getReleaseVariable, id)
	var i ReleaseVariable
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.CreatedAt,
	)
	return i, err
}

const listReleaseVariablesByRelease = `-- name: ListReleaseVariablesByRelease :many
SELECT id, release_id, name, value, environment_id, created_at FROM release_variables WHERE release_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListReleaseVariablesByRelease(ctx context.Context, releaseID int64) ([]ReleaseVariable, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseVariablesByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseVariable
	for rows.Next() {
		var i ReleaseVariable
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Name,
			&i.Value,
			&i.EnvironmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReleaseVariable = `-- name: UpdateReleaseVariable :one
UPDATE release_variables SET release_id = ?, name = ?, value = ?, environment_id = ? WHERE id = ? RETURNING id, release_id, name, value, environment_id, created_at
`

type UpdateReleaseVariableParams struct {
	ReleaseID     int64          `json:"release_id"`
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateReleaseVariable(ctx context.Context, arg UpdateReleaseVariableParams) (ReleaseVariable, error) {
	row := q.db.QueryRowContext(ctx, updateReleaseVariable,
		arg.ReleaseID,
		arg.Name,
		arg.Value,
		arg.EnvironmentID,
		arg.ID,
	)
	var i ReleaseVariable
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.CreatedAt,
	)
	return i, err
}
