// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: steps.sql

package db

import (
	"context"
)

const createStep = `-- name: CreateStep :one
INSERT INTO steps (project_id, name, script_body, sort_order) VALUES (?, ?, ?, ?) RETURNING id, project_id, name, script_body, sort_order, created_at
`

type CreateStepParams struct {
	ProjectID  int64  `json:"project_id"`
	Name       string `json:"name"`
	ScriptBody string `json:"script_body"`
	SortOrder  int64  `json:"sort_order"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (Step, error) {
	row := q.db.QueryRowContext(ctx, createStep,
		arg.ProjectID,
		arg.Name,
		arg.ScriptBody,
		arg.SortOrder,
	)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ScriptBody,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStep = `-- name: DeleteStep :exec
DELETE FROM steps WHERE id = ?
`

func (q *Queries) DeleteStep(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStep, id)
	return err
}

const getStep = `-- name: GetStep :one
SELECT id, project_id, name, script_body, sort_order, created_at FROM steps WHERE id = ?
`

func (q *Queries) GetStep(ctx context.Context, id int64) (Step, error) {
	row := q.db.QueryRowContext(ctx, getStep, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ScriptBody,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listStepsByProject = `-- name: ListStepsByProject :many
SELECT id, project_id, name, script_body, sort_order, created_at FROM steps WHERE project_id = ? ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListStepsByProject(ctx context.Context, projectID int64) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, listStepsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ScriptBody,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStep = `-- name: UpdateStep :one
UPDATE steps SET name = ?, script_body = ?, sort_order = ? WHERE id = ? RETURNING id, project_id, name, script_body, sort_order, created_at
`

type UpdateStepParams struct {
	Name       string `json:"name"`
	ScriptBody string `json:"script_body"`
	SortOrder  int64  `json:"sort_order"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) (Step, error) {
	row := q.db.QueryRowContext(ctx, updateStep,
		arg.Name,
		arg.ScriptBody,
		arg.SortOrder,
		arg.ID,
	)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ScriptBody,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
