// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step_templates.sql

package db

import (
	"context"
)

const createStepTemplate = `-- name: CreateStepTemplate :one
INSERT INTO step_templates (name, script_body) VALUES (?, ?) RETURNING id, name, script_body, created_at
`

type CreateStepTemplateParams struct {
	Name       string `json:"name"`
	ScriptBody string `json:"script_body"`
}

func (q *Queries) CreateStepTemplate(ctx context.Context, arg CreateStepTemplateParams) (StepTemplate, error) {
	row := q.db.QueryRowContext(ctx, createStepTemplate, arg.Name, arg.ScriptBody)
	var i StepTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScriptBody,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStepTemplate = `-- name: DeleteStepTemplate :exec
DELETE FROM step_templates WHERE id = ?
`

func (q *Queries) DeleteStepTemplate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStepTemplate, id)
	return err
}

const getStepTemplate = `-- name: GetStepTemplate :one
SELECT id, name, script_body, created_at FROM step_templates WHERE id = ?
`

func (q *Queries) GetStepTemplate(ctx context.Context, id int64) (StepTemplate, error) {
	row := q.db.QueryRowContext(ctx, getStepTemplate, id)
	var i StepTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScriptBody,
		&i.CreatedAt,
	)
	return i, err
}

const listStepTemplates = `-- name: ListStepTemplates :many
SELECT id, name, script_body, created_at FROM step_templates ORDER BY name ASC
`

func (q *Queries) ListStepTemplates(ctx context.Context) ([]StepTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listStepTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepTemplate
	for rows.Next() {
		var i StepTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ScriptBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStepTemplate = `-- name: UpdateStepTemplate :one
UPDATE step_templates SET name = ?, script_body = ? WHERE id = ? RETURNING id, name, script_body, created_at
`

type UpdateStepTemplateParams struct {
	Name       string `json:"name"`
	ScriptBody string `json:"script_body"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateStepTemplate(ctx context.Context, arg UpdateStepTemplateParams) (StepTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateStepTemplate, arg.Name, arg.ScriptBody, arg.ID)
	var i StepTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScriptBody,
		&i.CreatedAt,
	)
	return i, err
}
