// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variables.sql

package db

import (
	"context"
	"database/sql"
)

const createVariable = `-- name: CreateVariable :one
INSERT INTO variables (project_id, name, value, environment_id) VALUES (?, ?, ?, ?) RETURNING id, project_id, name, value, environment_id, created_at
`

type CreateVariableParams struct {
	ProjectID     int64          `json:"project_id"`
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
}

func (q *Queries) CreateVariable(ctx context.Context, arg CreateVariableParams) (Variable, error) {
	row := q.db.QueryRowContext(ctx, createVariable,
		arg.ProjectID,
		arg.Name,
		arg.Value,
		arg.EnvironmentID,
	)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVariable = `-- name: DeleteVariable :exec
DELETE FROM variables WHERE id = ?
`

func (q *Queries) DeleteVariable(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVariable, id)
	return err
}

const getVariable = `-- name: GetVariable :one
SELECT id, project_id, name, value, environment_id, created_at FROM variables WHERE id = ?
`

func (q *Queries) GetVariable(ctx context.Context, id int64) (Variable, error) {
	row := q.db.QueryRowContext(ctx, getVariable, id)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.CreatedAt,
	)
	return i, err
}

const listVariablesByProject = `-- name: ListVariablesByProject :many
SELECT id, project_id, name, value, environment_id, created_at FROM variables WHERE project_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListVariablesByProject(ctx context.Context, projectID int64) ([]Variable, error) {
	rows, err := q.db.QueryContext(ctx, listVariablesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variable
	for rows.Next() {
		var i Variable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Value,
			&i.EnvironmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariable = `-- name: UpdateVariable :one
UPDATE variables SET name = ?, value = ?, environment_id = ? WHERE id = ? RETURNING id, project_id, name, value, environment_id, created_at
`

type UpdateVariableParams struct {
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateVariable(ctx context.Context, arg UpdateVariableParams) (Variable, error) {
	row := q.db.QueryRowContext(ctx, updateVariable,
		arg.Name,
		arg.Value,
		arg.EnvironmentID,
		arg.ID,
	)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.CreatedAt,
	)
	return i, err
}
